name: restaurantzz
description: "Your go-to app for finding epic eats, hidden gems, and must-try spots. Discover, vibe, and savor effortlessly."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.7
  flutter: ">=3.38.6"

dependencies:
  flutter:
    sdk: flutter

  # Logging
  logger: ^2.6.1

  # State Management
  provider: ^6.1.5+1

  # Networking
  http: ^1.3.0
  url_launcher: ^6.3.0

  # UI
  flutter_rating_bar: ^4.0.1
  readmore: ^3.0.0
  flutter_launcher_icons: ^0.14.4

  # Local storage
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^1.0.1+1

  # Scheduler
  flutter_local_notifications: ^19.4.2
  flutter_timezone: ^5.0.0
  timezone: ^0.10.1

  workmanager: ^0.9.0+3

  flutter_junitreport:
    git:
      url: https://github.com/waffiqaziz/flutter-junitreport.git
      ref: 2.0.7-dev.2

executables:
  tojunit:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  sqflite_common_ffi: ^2.3.6
  mocktail: ^1.0.4

  network_image_mock: ^2.1.1

  # runner
  build_runner: ^2.8.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200

flutter_launcher_icons:
  android: false # set using default .xml
  ios: true
  image_path: "assets/icon/icon-512-maskable.png"
